apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - admin-secret.yaml
  - tls-secret.yaml

configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomize-config.yaml
