apiVersion: v1
data:
    GF_SECRET_ADMIN_PASSWORD: ENC[AES256_GCM,data:qdyrYXzyo/vz0nDPBRIlB3oCqu8=,iv:tBRell5G8A4hfXhcatgGnXk8boeIAiro4btibQCqD1k=,tag:89U0yWAmzXkJ0VBKFTHU8Q==,type:str]
    GF_SECRET_ADMIN_USER: ENC[AES256_GCM,data:q9Ifro3d1MFrzGeu,iv:CdoeOBAylXbLzpeSDYOHchIUjwO7ptSSxe0sYwKfV7c=,tag:Rw5JLvSj6v6hhv1WAMe+Ng==,type:str]
kind: Secret
metadata:
    name: kube-prometheus-stack-grafana-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxl0zx7jgfafes0x23rr24s7cwdfj0ntfrj30pryyn745dcyfc0qycqj7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aFlpb1hIVlBOT2FUNFlr
            bml4Ly93WmVsc2tvYmpqaXhYN0hIS0tlM0J3CkhDWnVRL2NMYkNrVHFjZnNoQlFL
            V0wyTjNmaDFsMHNsaGUwM0pRZXhxcFUKLS0tIG1YaWtxbXZOQWxzbnNLWXY5S2Qx
            Sm9VL1FrLzYzZFJZdG5RYlFVVGMrSUEK3eQovJZWvyRNyTEgQiyZPa92XaSI0I3K
            joqrcDHHn+90pgZ4Uhh7tx4jeiO+XBSk8k+tfPSu6ih6ME8RAjsvLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T10:32:02Z"
    mac: ENC[AES256_GCM,data:n/GOlZUkeq3Uu86W3PVaMLhxbVewrIuKYxBzcYULtwo5Qjzan+JuNWri7ElV3b6i63/G8bIMe9t1eUl49KlVkT8lfmGqKwXyaQrqbWPB5w6zSJNSFm0X69qu68rfulGfqAMORTSNocq2VtXHW/9vUbMo4EUF8Wj34yZYb/laV38=,iv:/uKcB1zgKKAr5SnCqS9ClagrsNB9Tmpgz9CjTIr3tkI=,tag:dEIQ4Tgv+6PoISvw5BtBjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
