apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - linkding-env-secret.yaml
  - cloudflare-secret.yaml
  - cloudflare.yaml

configMapGenerator:
  - name: cloudflare-values
    files:
      - config.yaml=cloudflare-config.yaml
configurations:
  - kustomize-config.yaml
