apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
data:
  values.yaml: |
    grafana:
      adminPassword: grafana
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grs.maslias.com
        #
        # tls:
        #   - secretName: grafana-tls-secret
        #     hosts:
        #       - grs.maslias.com
