apiVersion: v1
kind: ConfigMap
metadata:
    name: kube-prometheus-stack-values-adminpassword
data:
    values.yaml: ENC[AES256_GCM,data:3/s6Mqikqtt/CJmsl7bWONK3eUPZlQf2Nnju8W5znsliNsEA2EYPf6JymOVB,iv:U47bJYBeVrK0lNoE0kHdkw2CxWpulsg9sTnEZlj6cic=,tag:nxacgW7KMbf/XLD4C8gMTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxl0zx7jgfafes0x23rr24s7cwdfj0ntfrj30pryyn745dcyfc0qycqj7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRUczaUl2UWI2QWFrUFFM
            eDM1NkhXb2pWcUdDMlg2MUM3b0orVmh6QnpZCnp6ellROGJteGl5ZGN5NDF4UDdn
            N0t4b2xhQkZkMk8rOTFKZDUvTFBCdzgKLS0tIEREWHN4ZWN0NjRvOU4rbHBzZDVy
            cUUrcGZwUE1EclBVQUhFVCtYQkJlRGsKjTfP7hcHkIYfidln9X7SfCQ+nmQl/oMc
            Qtpi9OcuxaCZwqydtXMDNGMe/XukJGze/HqUTRz0t9OCJoElPqim+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:13:33Z"
    mac: ENC[AES256_GCM,data:EFXBt12aoErcOe8IMvCZS7bJJCEbgoXLcptVEqModV/WdtKeGZxdmupIAWpMV31bC2IUBZIPqsWRuowl+kdHXB7400BMyR2e6wrDIZBfnUUc0tiAnhcTpWaxA0t5S0Xg6etdS6eH8lU0LNOjzx7Ff+MMyVIug94mDSNn9KaOYak=,iv:/PzBNObzQ1zQHmiM6EWRVD3vUT96YOkcuJhAEPr4DjA=,tag:vkmrh33NFd4QqyOVfKdZng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
